- name: Install VSCode
  hosts: localhost
  become: true
  tasks:
  - name: Check if VSCode is installed
    ansible.builtin.stat:
      path: /usr/bin/code
    register: vscode_stat
  - name: Check if VSCode deb is downloaded
    ansible.builtin.stat:
      path: /tmp/code.deb
    register: vscode_deb_stat
  - name: Download VSCode Debian Package
    ansible.builtin.get_url:
      url: https://vscode.download.prss.microsoft.com/dbazure/download/stable/6f17636121051a53c88d3e605c491d22af2ba755/code_1.103.2-1755709794_amd64.deb
      dest: /tmp/code.deb
      owner: null
      group: null
    register: vscode_deb
    when: vscode_stat.stat.exists == False and vscode_deb_stat.stat.exists == False
  - name: Install VSCode
    ansible.builtin.shell:
      cmd: dpkg -i /tmp/code.deb
