- name: Install Wireguard
  hosts: localhost
  become: true
  tasks:
  - name: install wireguard
    ansible.builtin.apt:
      name: wireguard
      update_cache: 'yes'
  - name: install wg-tools
    ansible.builtin.apt:
      name: wireguard-tools
      update_cache: 'yes'
