- name: Install Tools
  hosts: localhost
  tasks:
  - name: Check if /home/kali/tools exists
    ansible.builtin.stat:
      path: /home/kali/tools
    register: tools_stat
  - name: Create /home/kali/tools
    ansible.builtin.file:
      path: /home/kali/tools
      state: directory
      owner: kali
      group: kali
    when: tools_stat.stat.exists == false
  - name: Check if /home/kali/tools/standalone exists
    ansible.builtin.stat:
      path: /home/kali/tools/standalone
    register: standalone_stat
  - name: Create /home/kali/tools/standalone
    ansible.builtin.file:
      path: /home/kali/tools/standalone
      state: directory
      owner: kali
      group: kali
    when: standalone_stat.stat.exists == false
  - name: pipx install tools
    ansible.builtin.shell:
      cmd: |-
        for d in /home/kali/tools/*/; do
            if [ -f "$d/setup.py" ] || [ -f "$d/pyproject.toml" ]; then
                echo "Installing $d with pipx"
                pipx install "$d"
            fi
        done
